### ISSUE TITLE
Inception v3

### ISSUE THREAD

**Issue by austinmw** [PPPW/deep-learning-random-explore#5]
Hi, were you able to get a Learner to work for either torchvision inception_v3 or cadene inceptionv3? I'm able to use Learner directly rather than create_cnn, but learn.summary() fails with `AttributeError: 'NoneType' object has no attribute 'shape'`

**Comment by PPPW** [comment]
Hi @austinmw, I have added a hacky example to use torchvision inception v3 for your reference. I'm not sure about your error, need more info from the stack trace.

**Comment by austinmw** [comment]
@PPPW Thanks! That would have probably taken me quite a while to figure out.
