### ISSUE TITLE
EfficientNet implementation in pretrainedmodels

### ISSUE THREAD

**Issue by saurabh502** [PPPW/deep-learning-random-explore#7]
Hi,
Can we implement new EfficientNet in this package?
Details: [https://ai.googleblog.com/2019/05/efficientnet-improving-accuracy-and.html]

I tried implementing it with Fastai, but getting error.
Below is the code:
`!pip install efficientnet_pytorch
from efficientnet_pytorch import EfficientNet

def efficientnet(model_name='efficientnet-b0',**kwargs):
    return EfficientNet.from_pretrained(model_name).to(device)

### getting error here
learn = cnn_learner(data_large, efficientnet, metrics=accuracy, model_dir=MODEL_PATH)`

Error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-8373c77d5d9e> in <module>()
----> 1 learn = cnn_learner(data_large, efficientnet, metrics=accuracy, model_dir=MODEL_PATH)

/opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in cnn_learner(data, base_arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, init, concat_pool, **kwargs)
     95     meta = cnn_config(base_arch)
     96     model = create_cnn_model(base_arch, data.c, cut, pretrained, lin_ftrs, ps=ps, custom_head=custom_head,
---> 97         split_on=split_on, bn_final=bn_final, concat_pool=concat_pool)
     98     learn = Learner(data, model, **kwargs)
     99     learn.split(split_on or meta['split'])

/opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in create_cnn_model(base_arch, nc, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, concat_pool)
     81         split_on:Optional[SplitFuncOrIdxList]=None, bn_final:bool=False, concat_pool:bool=True):
     82     "Create custom convnet architecture"
---> 83     body = create_body(base_arch, pretrained, cut)
     84     if custom_head is None:
     85         nf = num_features_model(nn.Sequential(*body.children())) * (2 if concat_pool else 1)

/opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in create_body(arch, pretrained, cut)
     53 def create_body(arch:Callable, pretrained:bool=True, cut:Optional[Union[int, Callable]]=None):
     54     "Cut off the body of a typically pretrained `model` at `cut` (int) or cut the model as specified by `cut(model)` (function)."
---> 55     model = arch(pretrained)
     56     cut = ifnone(cut, cnn_config(arch)['cut'])
     57     if cut is None:

<ipython-input-19-14bfb870ef12> in efficientnet(model_name, **kwargs)
      1 def efficientnet(model_name='efficientnet-b0',**kwargs):
----> 2     return EfficientNet.from_pretrained(model_name).to(device)

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/model.py in from_pretrained(cls, model_name)
    185     @classmethod
    186     def from_pretrained(cls, model_name):
--> 187         model = EfficientNet.from_name(model_name)
    188         load_pretrained_weights(model, model_name)
    189         return model

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/model.py in from_name(cls, model_name, override_params)
    179     @classmethod
    180     def from_name(cls, model_name, override_params=None):
--> 181         cls._check_model_name_is_valid(model_name)
    182         blocks_args, global_params = get_model_params(model_name, override_params)
    183         return EfficientNet(blocks_args, global_params)

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/model.py in _check_model_name_is_valid(cls, model_name, also_need_pretrained_weights)
    201         num_models = 4 if also_need_pretrained_weights else 8
    202         valid_models = ['efficientnet_b'+str(i) for i in range(num_models)]
--> 203         if model_name.replace('-','_') not in valid_models:
    204             raise ValueError('model_name should be one of: ' + ', '.join(valid_models))

AttributeError: 'bool' object has no attribute 'replace'`

**Comment by PPPW** [comment]
Hi @saurabh502,
I have added a sections for `EfficientNet`, maybe you can test it out?

**Comment by saurabh502** [comment]
Hi @PPPW ,
Thank you for adding EfficientNet !
Yes, implementation is working fine, but the results are very poor when compared to other architecture.
For example:
**se_resnext101**

epoch | train_loss | valid_loss | accuracy | time
-- | -- | -- | -- | --
0 | 1.396840 | 1.705229 | 0.500873 | 04:27
1 | 1.223736 | 1.138597 | 0.556719 | 04:23
2 | 1.047213 | 1.103554 | 0.565445 | 04:22
3 | 1.006950 | 35.257614 | 0.509599 | 04:23
4 | 0.919751 | 8.823987 | 0.577661 | 04:22
5 | 0.857063 | 4.468378 | 0.621291 | 04:23

**Efficientnet**

epoch	train_loss	valid_loss	time
0	1.527694	2.646757	02:39
1	1.890092	4.892186	02:35
2	2.100172	25.513174	02:36
3	1.750045	2.835118	02:35
4	1.875886	7.877785	02:35
5	1.323173	3.724878	02:35
6	1.249951	1.918557	02:33

Any thoughts on this?

Thanks!

**Comment by saurabh502** [comment]
Hi @PPPW ,
I checked it , it is working for me, thank you for your help!

**Comment by PPPW** [comment]
Hi @saurabh502, 
Sounds good! Thanks for testing, I'm glad it helps!
